/**
 * careers.js — career catalogue (Stream B extraction). Shifts use day indices
 * 0..6; salary fields keep both legacy and current names for compatibility.
 */

// All jobs share one schedule: Monday–Friday (weekdays 0–4), 08:00–17:00.
// Weekends (weekdays 5–6) are off. Shared read-only array.
const WORK_WEEK = [0, 1, 2, 3, 4].map(day => ({ day, start: 8, end: 17 }));

export const CAREERS = [
  {
    id: 'unemployed',
    label: 'Unemployed',
    emoji: '-',
    icon: '-',
    levels: 1,
    requiredSkill: {},
    skillReq: {},
    shifts: [],
    salaryBase: 0,
    salaryPerLevel: 0,
    salaryPerDay: 0,
  },
  {
    id: 'artist',
    label: 'Artist',
    emoji: 'Art',
    icon: 'Art',
    levels: 10,
    requiredSkill: { creativity: 2 },
    skillReq: { creativity: 2 },
    skillRequired: 'creativity',
    shifts: WORK_WEEK,
    salaryBase: 120,
    salaryPerLevel: 40,
    salaryStep: 40,
    salaryPerDay: 160,
  },
  {
    id: 'scientist',
    label: 'Scientist',
    emoji: 'Sci',
    icon: 'Sci',
    levels: 10,
    requiredSkill: { logic: 2 },
    skillReq: { logic: 2 },
    skillRequired: 'logic',
    shifts: WORK_WEEK,
    salaryBase: 180,
    salaryPerLevel: 60,
    salaryStep: 60,
    salaryPerDay: 240,
  },
  {
    id: 'chef',
    label: 'Chef',
    emoji: 'Chef',
    icon: 'Chef',
    levels: 10,
    requiredSkill: { cooking: 2 },
    skillReq: { cooking: 2 },
    skillRequired: 'cooking',
    shifts: WORK_WEEK,
    salaryBase: 150,
    salaryPerLevel: 50,
    salaryStep: 50,
    salaryPerDay: 200,
  },
  {
    id: 'programmer',
    label: 'Programmer',
    emoji: 'Code',
    icon: 'Code',
    levels: 10,
    requiredSkill: { logic: 2 },
    skillReq: { logic: 2 },
    skillRequired: 'logic',
    shifts: WORK_WEEK,
    salaryBase: 200,
    salaryPerLevel: 80,
    salaryStep: 80,
    salaryPerDay: 280,
  },
  {
    id: 'athlete',
    label: 'Athlete',
    emoji: 'Fit',
    icon: 'Fit',
    levels: 10,
    requiredSkill: { fitness: 2 },
    skillReq: { fitness: 2 },
    skillRequired: 'fitness',
    shifts: WORK_WEEK,
    salaryBase: 160,
    salaryPerLevel: 55,
    salaryStep: 55,
    salaryPerDay: 215,
  },
];
